# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/new/bear.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sprite.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/llamaOne.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/llamaTwo.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/llamaThree.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_7.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_8.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_2.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_6.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_5.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_4.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/h_3.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_04.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_10.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_17.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_01.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_12.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_15.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_18.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_07.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_20.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_16.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_11.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_14.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_13.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_03.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_02.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_19.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_08.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_21.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_06.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_05.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_09.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_08.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_03.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_04.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_05.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_02.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_07.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_01.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/eat_06.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_3.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_4.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_5.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_2.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_7.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/scan_6.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_02.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_07.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_01.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_12.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_03.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_04.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_10.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_05.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_11.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_08.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_09.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/shower_06.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_3.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_0.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_6.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_2.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_4.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sleep_5.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/bond.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/instructions0.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/instructions1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower22.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep14.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep19.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep01.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower19.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep06.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower06.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower00.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower13.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep23.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep10.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower10.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep07.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower15.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower09.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep02.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep15.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower23.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower05.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep11.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower18.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower14.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower01.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep20.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower03.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep08.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower20.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep16.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower08.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep03.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep12.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep17.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower02.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower17.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower11.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower04.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep21.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower21.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower07.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep04.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep18.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep13.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower12.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep00.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep05.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep22.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barShowermem/barShower16.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/barSleepMEM/barSleep09.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/idle_1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/idle_2.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/die.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad3.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad5.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad0.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad6.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad2.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad1.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/sad4.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/area51.mem
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/imports/Downloads/food_00.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/new/vga_controller.v
  C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/sources_1/new/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/constrs_1/imports/Maheswari_and_Britney_s26/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Student/Desktop/Maheswari_and_Britney_s26/project_4/project_4.srcs/constrs_1/imports/Maheswari_and_Britney_s26/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
